blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

website/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from django.conf.urls.static import static

from django.conf import settings
from portfolio import views
from cv import views as cv_views
from contact import views as contact_views

urlpatterns = [
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', views.home, name='home'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('cv/', cv_views.cv, name='cv'),
    path('about/', cv_views.about, name='about'),
    path('contact/', contact_views.contact, name='contact'),
    path('contact/success', contact_views.success, name='success'),
    path('blog/', include('blog.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Blog(models.Model):
    title = models.CharField(_('title'), max_length=200)
    teaser = models.TextField(_('teaser'), default='', max_length=300)
    description = models.TextField(_('description'), default='')
    date = models.DateField()

contact/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def posts(request):
    blog_counts = Blog.objects.count()
    blogs = Blog.objects.order_by('-date')
    print(blogs)
    return render(request, 'blog/posts.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

contact/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.mail import send_mail

from .form import NameForm


def success(request):
    return render(request, 'contact/success.html')

def contact(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            send_mail(
                form.data['name'] + ' | ' + form.data['subject'],
                form.data['message'],
                form.data['email'],
                ['thibault.montel@gmail.com'],
                fail_silently=False,
            )
            return HttpResponseRedirect('success')

        # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'contact/contact.html', {'form': form})

cv/views.py
from django.shortcuts import render


def cv(request):
    return render(request, 'cv/cv.html')


def about(request):
    return render(request, 'cv/about.html')

portfolio/views.py
from django.shortcuts import render
from .models import Project
from django.http import HttpResponseRedirect
from django.utils import translation
from django.views.generic.base import View
from django.conf import settings
from django.shortcuts import redirect


def home(request):
    return render(request, 'portfolio/home.html')


def portfolio(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/portfolio.html', {'projects': projects})

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block content %}

    <br>
    <br>

<h2 class="mb-5">
    <a href="{% url 'blog:posts' %}">Blog</a> /
    {{ blog.title }}
</h2>

<h5 class="text-muted">{{ blog.date|date:'F jS Y' }}</h5>

<h1 id="blogdetailtitle">{{ blog.title }}</h1>


{{ blog.description|safe }}

{% endblock %}

blog/templates/blog/posts.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Thibault has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.teaser|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

contact/templates/contact/contact.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block content %}

<!-- ======= Contact Section ======= -->
  <section id="contact" class="contact">
    <div class="container">

      <div class="section-title">
        <h2>Contact</h2>
        <p>{% trans "Contact Me" %}</p>
      </div>

      <div class="row mt-2">

        <div class="col-md-6 d-flex align-items-stretch">
          <div class="info-box">
            <i class="bx bx-map"></i>
            <h3>{% trans "My Address" %}</h3>
            <p>Saint-Bruno-de-Montarville, QC</p>
          </div>
        </div>

        <div class="col-md-6 mt-4 mt-md-0 d-flex align-items-stretch">
          <div class="info-box">
            <i class="bx bx-share-alt"></i>
            <h3>{% trans "Social Profiles" %}</h3>
            <div class="social-links">
                <a href="https://github.com/tmontel" class="github" target="_blank" ><i class="bi bi-github"></i></a>
                <a href="https://www.linkedin.com/in/thibaultmontel/" class="linkedin"><i class="bi bi-linkedin"></i></a>
                <a href="mailto:thibault.montel@gmail.com" class="mailbox"><i class="bi bi-mailbox"></i></a>
                <a href="https://twitter.com/thibaultmontel"  target="_blank" class="twitter"><i class="bi bi-twitter"></i></a>
            </div>
          </div>
        </div>

        <div class="col-md-6 mt-4 d-flex align-items-stretch">
          <div class="info-box">
            <i class="bx bx-envelope"></i>
            <h3>{% trans "Email Me" %}</h3>
            <p>thibault.montel@gmail.com</p>
          </div>
        </div>
        <div class="col-md-6 mt-4 d-flex align-items-stretch">
          <div class="info-box">
            <i class="bx bx-phone-call"></i>
            <h3>{% trans "Call Me" %}</h3>
            <p>+1 438-885-1660</p>
          </div>
        </div>
      </div>

      <form action="{% url 'contact' %}" method="post" role="form" class="php-email-form mt-4">{% csrf_token %}
        <div class="row">
          <div class="col-md-6 form-group">
            <input type="text" name="name" class="form-control" id="name" placeholder="{% trans "Your Name" %}" required>
          </div>
          <div class="col-md-6 form-group mt-3 mt-md-0">
            <input type="email" class="form-control" name="email" id="email" placeholder="{% trans "Your Email" %}" required>
          </div>
        </div>
        <div class="form-group mt-3">
          <input type="text" class="form-control" name="subject" id="subject" placeholder="{% trans "Subject" %}" required>
        </div>
        <div class="form-group mt-3">
          <textarea class="form-control" name="message" rows="5" placeholder="{% trans "Message" %}" required></textarea>
        </div>
        <div class="my-3">
          <div class="loading">{% trans "Loading" %}</div>
          <div class="error-message"></div>
          <div class="sent-message">{% trans "Your message has been sent. Thank you!" %}</div>
        </div>
        <div class="text-center"><button type="submit">{% trans "Send Message" %}</button></div>
      </form>

    </div>
  </section><!-- End Contact Section -->

{% endblock %}

contact/templates/contact/success.html
OK

cv/templates/cv/cv.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block content %}

     <!-- ======= Resume Section ======= -->
  <section id="resume" class="resume">
    <div class="container">

      <div class="section-title">
        <h2>{% trans "Resume" %}</h2>
        <p>{% trans "Check My Resume" %}</p>
      </div>

      <div class="row">
        <div class="col-lg-6">
          <h3 class="resume-title">{% trans "Sumary" %}</h3>
          <div class="resume-item pb-0">
            <h4>Thibault Montel</h4>
            <p><em>{% trans "Innovative, time-conscious back-end developer with over 15 years of experience designing and developing user-centric software from initial concept to final, polished deliverable." %}.</em></p>
            <p>
            <ul>
              <li>Saint-Bruno-de-Montarville, QC</li>
              <li>(438) 885-1660</li>
              <li>thibault.montel@gmail.com</li>
            </ul>
            </p>
          </div>
            <h3 class="resume-title">{% trans "Professional Experience" %}</h3>
          <div class="resume-item">
            <h4>{% trans "Lead Backend Developer" %} - SAQ.com</h4>
            <h5>2018 - {% trans "Now" %}</h5>
            <p><em>Valtech / Absolunet, {% trans "Montreal" %}, QC </em></p>
            <p>
            <ul>
              <li>{% trans "Architecture, implementation, maintenance and evolution of the SAQ.com site" %}</li>
              <li>{% trans "System Integration, Rest API, JWT Token" %}</li>
              <li>{% trans "Middleware, Messaging queue" %}</li>
              <li>{% trans "Rabbit MQ, Artemis Active MQ- Azure Storage" %}</li>
              <li>{% trans "Payment system management, Fraud detection" %}</li>
              <li>{% trans "Fastly, Varnish, VCL Snippet and Redis" %}</li>
              <li>{% trans "MySQL" %}</li>
              <li>{% trans "Elastic search, Logstash" %}</li>
              <li>{% trans "SAML Authentication" %}</li>
              <li>{% trans "Unit testing" %}</li>
            </ul>
            </p>
          </div>
          <div class="resume-item">
            <h4>{% trans "Lead Backend Developer" %}</h4>
            <h5>2016 - 2018</h5>
            <p><em>Valtech / Absolunet, {% trans "Montreal" %}, QC </em></p>
            <p>
            <ul>
              <li>{% trans "Development of Magento 1 and 2 e-commerce sites" %}</li>
              <li>{% trans "Design, development and maintenance of e-commerce platforms" %}</li>
              <li>{% trans "Functional analysis" %}</li>
              <li>{% trans "Database design" %}</li>
              <li>{% trans "User technical support" %}</li>
              <li>{% trans "Documentation writing" %}</li>
              <li>{% trans "Customizations / Evolutions" %}</li>
              <li>{% trans "System integrations" %}</li>
              <li>{% trans "Monitoring" %}</li>
              <li>{% trans "Performance Optimization - Security Management" %}</li>
            </ul>
            </p>
          </div>
          <div class="resume-item">
            <h4>{% trans "Digital Marketing Developer" %}</h4>
            <h5>2014 - 2016</h5>
            <p><em>iProspect / NVI, {% trans "Montreal" %}, QC</em></p>
            <p>
            <ul>
              <li>{% trans "Creating Google Docs Scripts" %}</li>
              <li>{% trans "Creating Adwords Scripts" %}</li>
              <li>{% trans "DoubleClick Studio Dynamic Banners" %}</li>
              <li>{% trans "Google Analytics measurement plan and implementation guide" %}</li>
              <li>{% trans "Google Tag Manager and Google Analytics setup" %}</li>
              <li>{% trans "Implementation of internal tools" %}</li>
              <li>{% trans "Monitoring and evolution of the company's ERP" %}</li>
            </ul>
            </p>
          </div>
          <div class="resume-item">
            <h4>{% trans "Backend Developer" %}</h4>
            <h5>2010 - 2014</h5>
            <p><em>NVI, {% trans "Montreal" %}, QC</em></p>
            <p>
            <ul>
              <li>{% trans "Design, development and maintenance of an ERP with Zend Framework / Doctrine" %}</li>
              <li>{% trans "Functional analysis" %}</li>
              <li>{% trans "Database design" %}s</li>
              <li>{% trans "User technical support" %}</li>
              <li>{% trans "Documentation writing" %}</li>
              <li>{% trans "Google Analytics" %}</li>
              <li>{% trans "Joomla" %}</li>
              <li>{% trans "Magento" %}</li>
            </ul>
            </p>
          </div>
          <div class="resume-item">
            <h4>{% trans "Backend Developer" %}</h4>
            <h5>2009 - 2010</h5>
            <p><em>Inpix, {% trans "Montreal" %}, QC</em></p>
            <p>
            <ul>
              <li>{% trans "Implementation of a personalized newsletter program for Bestbuy" %}</li>
              <li>{% trans "Development of various contests for Bestbuy and Les Ailes de la Mode" %}</li>
              <li>{% trans "Development of Wordpress plugins for the websites of the Opéra de Montreal, the Noel au Printemps Foundation and Sonotechnique" %}</li>
              <li>{% trans "Development of fan pages as well as several Facebook games for Educ'Alcool / Pocheville" %}</li>
              <li>{% trans "Works on the Google map API" %}</li>
              <li>{% trans "Work on an online registration and tracking system for Telus rep events" %}</li>
            </ul>
            </p>
          </div>
          <div class="resume-item">
            <h4>{% trans "Backend Developer" %}</h4>
            <h5>2009</h5>
            <p><em>{% trans "Freelance" %}, {% trans "Montreal" %}, QC</em></p>
            <p>
            <ul>
              <li>{% trans "Development of several streaming sites" %}</li>
              <li>{% trans "Wordpress multi-user blog" %}</li>
              <li>{% trans "Linux system administration" %}</li>
            </ul>
            </p>
          </div>
          <div class="resume-item">
            <h4>{% trans "Flash Developer" %}</h4>
            <h5>2009</h5>
            <p><em>Vortex Solution, {% trans "Montreal" %}, QC</em></p>
            <p>
            <ul>
              <li>{% trans "AS1 / AS2 flash animation development" %}</li>
            </ul>
            </p>
          </div>
          <div class="resume-item">
            <h4>{% trans "Backend Developer" %} Java / PHP</h4>
            <h5>2007 - 2009</h5>
            <p><em>Prizee.com, Clermont-Ferrand, France</em></p>
            <p>
            <ul>
              <li>{% trans "Development and securing of online payment methods in PHP 5 (Credit card)" %}</li>
              <li>{% trans "Development and securing of online payment methods in JavaJ2EE / Webservices (Internet+)" %}</li>
              <li>{% trans "MySql database design and optimization" %}</li>
              <li>{% trans "Ajax development" %}</li>
              <li>{% trans "Development of game servers in Php" %}</li>
              <li>{% trans "General development on the Prizee.com website" %}</li>
              <li>{% trans "Setting up a dynamic graph system in Java" %}</li>
              <li>{% trans "Documentation writing" %}</li>
            </ul>
            </p>
          </div>
          <div class="resume-item">
            <h4>{% trans "System Administrator / Java Developer" %}</h4>
            <h5>2005 - 2006</h5>
            <p><em>Newtel, Clermont-Ferrand, France - {% trans "Intership" %}</em></p>
            <p>
            <ul>
              <li>{% trans "Design and implementation of a shared agenda / messaging management application in Java J2EE" %}</li>
              <li>{% trans "Administration Windows 2008 server edition" %}</li>
              <li>{% trans "Managing a remote application via Terminal Server" %}</li>
            </ul>
            </p>
          </div>
        </div>
        <div class="col-lg-6">
          <h3 class="resume-title">{% trans "Certifications" %}</h3>
          <div class="resume-item">
            <h4><a href="https://www.credly.com/badges/f25b0300-94b9-42a9-a0c7-979559807e35/public_url" target="_blank">PCAP – Certified Associate in Python Progamming</a></h4>
            <h5>2022</h5>
            <p><em>Python Institute</em></p>
          </div>
          <div class="resume-item">
            <h4><a href="https://www.credly.com/badges/6d5bc6a6-da64-4deb-85f9-64e7d02586d7/public_url" target="_blank">PCEP – Certified Entry-Level Python Programmer</a></h4>
            <h5>2022</h5>
            <p><em>Python Institute</em></p>
          </div>
          <h3 class="resume-title">{% trans "Education" %}</h3>
          <div class="resume-item">
            <h4>{% trans "IT Specialist" %}</h4>
            <h5>2006 - 2007</h5>
            <p><em>EPITECH - Le Kremlin Bicètre, France</em></p>
          </div>
          <div class="resume-item">
            <h4>{% trans "Bachelor's degree in Computer Systems and Software, Software Development" %}</h4>
            <h5>2005 - 2006</h5>
            <p><em>{% trans "Auvergne University" %} - Aurillac, France</em></p>
          </div>
          <div class="resume-item">
            <h4>{% trans "B.T.S. IRIS, Software Development and Networks, Software Development" %}</h4>
            <h5>2003 - 2005</h5>
            <p><em>{% trans "Auvergne University" %} - Aurillac, France</em></p>
          </div>
        </div>
      </div>

    </div>
  </section><!-- End Resume Section -->

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Thibault Montel</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static "portfolio/img/favicon.png" %}" rel="icon">
  <link href="{% static "portfolio/img/apple-touch-icon.png" %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static "portfolio/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "portfolio/vendor/bootstrap-icons/bootstrap-icons.css" %}" rel="stylesheet">
  <link href="{% static "portfolio/vendor/boxicons/css/boxicons.min.css" %}" rel="stylesheet">
  <link href="{% static "portfolio/vendor/glightbox/css/glightbox.min.css" %}" rel="stylesheet">
  <link href="{% static "portfolio/vendor/remixicon/remixicon.css" %}" rel="stylesheet">
  <link href="{% static "portfolio/vendor/swiper/swiper-bundle.min.css" %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static "portfolio/css/style.css" %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Personal - v4.7.0
  * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

      <h1><a href="{% url 'home' %}">Thibault Montel</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="mr-auto"><img src="{% static "portfolio/img/logo.png" %}" alt="" class="img-fluid"></a> -->
      <h2>{% trans "I'm a passionate <span>backend developer</span> from Saint-Bruno-de-Montarville" %}</h2>

      <nav id="navbar" class="navbar">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as languages %}

        <ul>
          <li><a class="nav-link active" href="{% url 'home' %}#header">{% trans "Home" %}</a></li>
          <li><a class="nav-link" href="{% url 'about' %}#about">{% trans "About" %}</a></li>
          <li><a class="nav-link" href="{% url 'cv' %}#resume">{% trans "Resume" %}</a></li>
          <!--<li><a class="nav-link" href="services">Services</a></li>-->
          <li><a class="nav-link" href="{% url 'portfolio' %}#portfolio">{% trans "Portfolio" %}</a></li>
          <li><a class="nav-link" href="{% url 'contact' %}#contact">{% trans "Contact" %}</a></li>
            <li>
                {% for lang_code, lang_name in languages %}
                  {% if lang_code != LANGUAGE_CODE %}
                    <a href="/{{ lang_code }}/"> {{ lang_name }}</a>
                  {% endif %}
                {% endfor %}
            </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->


      <div class="social-links">
        <a href="https://github.com/tmontel" class="github" target="_blank" ><i class="bi bi-github"></i></a>
        <a href="https://www.linkedin.com/in/thibaultmontel/" class="linkedin"><i class="bi bi-linkedin"></i></a>
        <a href="mailto:thibault.montel@gmail.com" class="mailbox"><i class="bi bi-mailbox"></i></a>
        <a href="https://twitter.com/thibaultmontel"  target="_blank" class="twitter"><i class="bi bi-twitter"></i></a>
      </div>

    </div>
  </header><!-- End Header -->

  {% block content %}{% endblock %}

  <div class="credits">
    <!-- All the links in the footer should remain intact. -->
    <!-- You can delete the links only if you purchased the pro version. -->
    <!-- Licensing information: https://bootstrapmade.com/license/ -->
    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/personal-free-resume-bootstrap-template/ -->
    <!--Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>-->
  </div>

  <!-- Vendor JS Files -->
  <script src="{% static "portfolio/vendor/purecounter/purecounter.js" %}"></script>
  <script src="{% static "portfolio/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "portfolio/vendor/glightbox/js/glightbox.min.js" %}"></script>
  <script src="{% static "portfolio/vendor/isotope-layout/isotope.pkgd.min.js" %}"></script>
  <script src="{% static "portfolio/vendor/swiper/swiper-bundle.min.js" %}"></script>
  <script src="{% static "portfolio/vendor/waypoints/noframework.waypoints.js" %}"></script>
  <script src="{% static "portfolio/vendor/php-email-form/validate.js" %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static "portfolio/js/main.js" %}"></script>

</body>

</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

portfolio/templates/portfolio/portfolio.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load i18n %}

{% block content %}

<!-- ======= Portfolio Section ======= -->
  <section id="portfolio" class="portfolio">
    <div class="container">

      <div class="section-title">
        <h2>Portfolio</h2>
        <p>{% trans "My Works" %}</p>
      </div>

      <!--<div class="row">
        <div class="col-lg-12 d-flex justify-content-center">
          <ul id="portfolio-flters">
            <li data-filter="*" class="filter-active">All</li>
            <li data-filter=".filter-app">App</li>
            <li data-filter=".filter-card">Card</li>
            <li data-filter=".filter-web">Web</li>
          </ul>
        </div>
      </div>-->

      <div class="row portfolio-container">

  {% for project in projects %}
        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
          <div class="portfolio-wrap">
            <img src="{{ project.image.url }}" class="img-fluid" alt="">
            <div class="portfolio-info">
              <h4>{{ project.title }}</h4>
              <p>{{ project.description }}</p>
              <div class="portfolio-links">
                <a href="{{ project.image.url }}" data-gallery="portfolioGallery" class="portfolio-lightbox" title="{{ project.description }}3"><i class="bx bx-plus"></i></a>
                <a href="portfolio-details.html" data-gallery="portfolioDetailsGallery" data-glightbox="type: external" class="portfolio-details-lightbox" title="Portfolio Details"><i class="bx bx-link"></i></a>
              </div>
            </div>
          </div>
        </div>
  {% endfor %}

      </div>

    </div>
  </section><!-- End Portfolio Section -->

{% endblock %}